---
title: Manifesto
author: Giulia Solinas and Christoph Feest
date: '2020-10-30'
slug: []
categories: []
tags:
  - Manifesto
---

We are starting the Diagonalising blog with this short manifesto, setting out our ambition and rationale for ‘going public’. 

Everything that can be digitalised will be digitalised. Many areas of public and private life are changing, some gradually, others abruptly, often intersecting with other megatrends. We want the Diagonalising blog to be an outlet where we describe patterns we observe, where we bring clarity into our observations and where we share our perspective.

Diagonalsing implies a foundation, a process, a destination. We are two professionals with experience crossing academia and translational research; we have learned to analyze complex relationships, simplify them, and represent the core ties through testable models. This process is iterative, dynamic, error-prone and it may leave you opposite of the origin. Our destination is a better understanding, a new approach or fresh insight. 

Blogging is reaching out. In a rather undigitized era, Alexander von Humboldt combined daring scientific fieldwork with popular writing that allowed him to reach out beyond the academic community, addressing a wider audience and popularising many aspects of science. Fast forward two centuries and there are countless ways to engage. The Diagonalising blog is ours.

We are blogging through projections and snippets. These two types of posts are the bones of our contributions. Projections develop a point-of-view and start a conversation; snippets collect one or more short observations, things we take note of.

Let’s get started, join the conversation.